sapling:
  mybatis:
    # 扫描 mapper 的根路径，同 @MapperScan
    base-package: com.sapling
    # 是否开启默认字段填充，默认为false。开启后，会自动在执行 insert 和 update 语句时，自动插入或更新 createTime 和 updateTime 字段
    common-field-value-auto-fill-enable: false
mybatis-plus:
  mapper-locations: classpath*:mappers/**/*.xml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.126.130:3306/framework?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123ABCdef*#
logging:
  level:
    com.sapling.module.system.infrastructure.gatewayImpl.database.mapper.policyDistribute: DEBUG   # 你的 Mapper 接口包路径
    org.springframework.jdbc: DEBUG # 打印 JDBC SQL